x-app-build: &app-build
  build:
    context: .
    dockerfile: Dockerfile
  env_file: .env
  environment:
    PYTHONPATH: /app
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  api:
    <<: *app-build
    restart: unless-stopped
    command: >
      uvicorn src.main:app
      --host 0.0.0.0
      --port 8000
      --proxy-headers
      --forwarded-allow-ips="*"
    expose:
      - "8000"
    networks:
      - backend
      - frontend
      - monitoring

  worker:
    <<: *app-build
    command: >
      celery -A worker.celery_app worker
      --loglevel=info
      --concurrency=3
      --queues=celery
    restart: unless-stopped
    networks:
      - backend
      - frontend

  beat:
    <<: *app-build
    command: >
      celery -A worker.celery_app beat
      --loglevel=info
      --schedule=/app/celerybeat/schedule.db
    volumes:
      - celerybeat_data:/app/celerybeat
    restart: unless-stopped
    networks:
      - backend

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: v2hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d v2hub"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - backend

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks:
      - backend

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/grafana.htpasswd:/etc/nginx/grafana.htpasswd:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped
    networks:
      - frontend
      - monitoring

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /bin/sh
    command: -c "while true; do certbot renew --webroot -w /var/www/certbot --quiet --deploy-hook 'docker exec nginx nginx -s reload'; sleep 12h; done"
    restart: unless-stopped
    networks:
      - frontend

      #  alloy:
      #    image: grafana/alloy:latest
      #    container_name: alloy
      #    restart: unless-stopped
      #    expose:
      #      - "12345"
      #    volumes:
      #      - ./monitoring/alloy/config.alloy:/etc/alloy/config.alloy
      #      - /var/run/docker.sock:/var/run/docker.sock # Docker API для дискавери
      #    command:
      #      - run
      #      - /etc/alloy/config.alloy
      #      - --server.http.listen-addr=0.0.0.0:12345 # включаем UI
      #      - --stability.level=generally-available
      #    privileged: true # нужно для чтения Docker сокета
      #    networks:
      #      - monitoring
      #
      #  loki:
      #    image: grafana/loki:latest
      #    container_name: loki
      #    restart: unless-stopped
      #    expose:
      #      - "3100"
      #    volumes:
      #      - ./monitoring/loki.yml:/etc/loki/local-config.yaml
      #      - lokidata:/loki
      #    networks:
      #      - monitoring
      #
      #  prometheus:
      #    image: prom/prometheus:latest
      #    container_name: prometheus
      #    restart: unless-stopped
      #    expose:
      #      - "9090"
      #    volumes:
      #      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      #      - prometheusdata:/prometheus
      #    networks:
      #      - monitoring
      #
      #  grafana:
      #    image: grafana/grafana:latest
      #    container_name: grafana
      #    restart: unless-stopped
      #    expose:
      #      - "3000"
      #    environment:
      #      - GF_SECURITY_ADMIN_USER=admin
      #      - GF_SECURITY_ADMIN_PASSWORD=admin
      #      - GF_SERVER_ROOT_URL=https://v2hub.link/grafana/
      #      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      #    volumes:
      #      - ./monitoring/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      #      - grafanadata:/var/lib/grafana
      #    networks:
      #      - frontend
      #      - monitoring

volumes:
  postgres_data:
  redis_data:
  celerybeat_data:
    #  grafanadata:
    #  prometheusdata:
    #  lokidata:

networks:
  backend:
    internal: true
  frontend:
  monitoring:
    internal: true
