"""initial schema

Revision ID: 0000
Revises:
Create Date: 2026-07-26 17:39:25.589127

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0000"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_cache",
        sa.Column(
            "url_hash",
            sa.String(length=64),
            nullable=False,
            comment="Blake2b hash of canonical URL",
        ),
        sa.Column("url", sa.Text(), nullable=False, comment="Original external subscription URL"),
        sa.Column(
            "raw_content",
            sa.Text(),
            nullable=True,
            comment="Newline-separated proxy configs (NULL = never fetched)",
        ),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Last successful fetch timestamp",
        ),
        sa.Column(
            "last_error", sa.Text(), nullable=True, comment="Last error message if fetch failed"
        ),
        sa.Column(
            "error_count",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Consecutive error count",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("url_hash"),
    )
    op.create_table(
        "proxy_configs",
        sa.Column(
            "config_hash",
            sa.String(length=64),
            nullable=False,
            comment="Blake2b hash of normalized config (without fragment)",
        ),
        sa.Column(
            "config_data",
            sa.Text(),
            nullable=False,
            comment="Proxy configuration URI without fragment",
        ),
        sa.Column(
            "protocol",
            sa.String(length=50),
            nullable=False,
            comment="Proxy protocol (vless, vmess, trojan, ss, etc.)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("config_hash"),
    )
    op.create_index(op.f("ix_proxy_configs_protocol"), "proxy_configs", ["protocol"], unique=False)
    op.create_table(
        "users",
        sa.Column(
            "user_hash",
            sa.String(length=255),
            nullable=False,
            comment="Stable hash derived from external user ID",
        ),
        sa.Column(
            "user_id",
            sa.BigInteger(),
            nullable=False,
            comment="Original user ID from external system",
        ),
        sa.Column(
            "api_token", sa.String(length=255), nullable=False, comment="API authentication token"
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("TRUE"),
            nullable=False,
            comment="Whether user account is active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_hash"),
    )
    op.create_index(op.f("ix_users_api_token"), "users", ["api_token"], unique=True)
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=True)
    op.create_table(
        "subscriptions",
        sa.Column(
            "token",
            sa.String(length=255),
            nullable=False,
            comment="Unique public identifier for subscription",
        ),
        sa.Column(
            "name",
            sa.String(length=64),
            nullable=False,
            comment="User-defined name for subscription",
        ),
        sa.Column("user_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "description",
            sa.String(length=64),
            nullable=True,
            comment="Optional description of subscription purpose",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_hash"], ["users.user_hash"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token"),
        sa.UniqueConstraint("user_hash", "name", name="uq_subscription_user_name"),
    )
    op.create_index("ix_subscriptions_user_hash", "subscriptions", ["user_hash"], unique=False)
    op.create_table(
        "config_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "subscription_token",
            sa.String(length=255),
            nullable=False,
            comment="Subscription this comment belongs to",
        ),
        sa.Column(
            "config_hash",
            sa.String(length=64),
            nullable=False,
            comment="Config this comment applies to",
        ),
        sa.Column(
            "comment",
            sa.String(length=255),
            nullable=False,
            comment="Comment text to append after # in config",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["config_hash"], ["proxy_configs.config_hash"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["subscription_token"], ["subscriptions.token"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subscription_token", "config_hash", name="uq_config_comment_sub_config"
        ),
    )
    op.create_index("ix_config_comments_config", "config_comments", ["config_hash"], unique=False)
    op.create_index(
        "ix_config_comments_subscription", "config_comments", ["subscription_token"], unique=False
    )
    op.create_table(
        "sources",
        sa.Column("subscription_token", sa.String(length=255), nullable=False),
        sa.Column(
            "id",
            sa.String(length=64),
            nullable=False,
            comment="Unique identifier for this source within subscription",
        ),
        sa.Column(
            "source_type",
            sa.String(length=50),
            nullable=False,
            comment="Type: CONFIG, EXTERNAL_URL, or INTERNAL_TOKEN",
        ),
        sa.Column(
            "config_hash",
            sa.String(length=64),
            nullable=True,
            comment="Reference to ProxyConfig (for CONFIG type)",
        ),
        sa.Column(
            "internal_token",
            sa.String(length=64),
            nullable=True,
            comment="Token for INTERNAL_TOKEN",
        ),
        sa.Column("external_url", sa.Text(), nullable=True, comment="URL for EXTERNAL_URL"),
        sa.Column(
            "order_index",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="User-defined ordering within subscription",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["config_hash"], ["proxy_configs.config_hash"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["subscription_token"], ["subscriptions.token"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("subscription_token", "id"),
    )
    op.create_index("ix_sources_config_hash", "sources", ["config_hash"], unique=False)
    op.create_index(
        "ix_sources_subscription_token", "sources", ["subscription_token"], unique=False
    )
    op.create_index("ix_sources_type", "sources", ["source_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sources_type", table_name="sources")
    op.drop_index("ix_sources_subscription_token", table_name="sources")
    op.drop_index("ix_sources_config_hash", table_name="sources")
    op.drop_table("sources")
    op.drop_index("ix_config_comments_subscription", table_name="config_comments")
    op.drop_index("ix_config_comments_config", table_name="config_comments")
    op.drop_table("config_comments")
    op.drop_index("ix_subscriptions_user_hash", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_api_token"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_proxy_configs_protocol"), table_name="proxy_configs")
    op.drop_table("proxy_configs")
    op.drop_table("external_cache")
    # ### end Alembic commands ###
