"""add provider models

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-06 19:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column(
            "provider_hash",
            sa.String(length=255),
            nullable=False,
            comment="Unique public identifier of the provider",
        ),
        sa.Column(
            "owner_hash",
            sa.String(length=255),
            nullable=False,
            comment="Hash of the user account that owns this provider",
        ),
        sa.Column(
            "provider_name", sa.String(length=64), nullable=False, comment="Unique provider name."
        ),
        sa.Column(
            "api_token",
            sa.String(length=255),
            nullable=False,
            comment="Provider API authentication token",
        ),
        sa.Column(
            "provider_url",
            sa.String(length=255),
            nullable=True,
            comment="Provider website or bot URL",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("TRUE"),
            nullable=False,
            comment="Whether the provider account is active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_hash"], ["users.user_hash"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("provider_hash"),
        sa.UniqueConstraint("owner_hash"),
        sa.UniqueConstraint("provider_name"),
    )
    op.create_index(op.f("ix_providers_api_token"), "providers", ["api_token"], unique=True)
    op.create_table(
        "provider_authorizations",
        sa.Column("provider_hash", sa.String(length=255), nullable=False),
        sa.Column("user_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("APPROVED", "REVOKED", name="providerauthorizationstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["provider_hash"], ["providers.provider_hash"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_hash"], ["users.user_hash"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("provider_hash", "user_hash", name="pk_provider_authorizations"),
    )
    op.create_index(
        "ix_provider_authorizations_user_hash",
        "provider_authorizations",
        ["user_hash"],
        unique=False,
    )
    op.add_column(
        "subscriptions",
        sa.Column(
            "provider_hash",
            sa.String(length=255),
            nullable=True,
            comment="Provider that owns this subscription. NULL for user-owned subscriptions.",
        ),
    )
    op.drop_constraint(op.f("uq_subscription_user_name"), "subscriptions", type_="unique")
    op.create_index(
        "uq_provider_subscription_name",
        "subscriptions",
        ["user_hash", "provider_hash", "name"],
        unique=True,
        postgresql_where=sa.text("provider_hash IS NOT NULL"),
        sqlite_where=sa.text("provider_hash IS NOT NULL"),
    )
    op.create_index(
        "uq_user_subscription_name",
        "subscriptions",
        ["user_hash", "name"],
        unique=True,
        postgresql_where=sa.text("provider_hash IS NULL"),
        sqlite_where=sa.text("provider_hash IS NULL"),
    )
    op.create_foreign_key(
        "fk_subscriptions_provider_hash_providers",
        "subscriptions",
        "providers",
        ["provider_hash"],
        ["provider_hash"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_subscriptions_provider_hash_providers", "subscriptions", type_="foreignkey"
    )
    op.drop_index(
        "uq_user_subscription_name",
        table_name="subscriptions",
        postgresql_where=sa.text("provider_hash IS NULL"),
        sqlite_where=sa.text("provider_hash IS NULL"),
    )
    op.drop_index(
        "uq_provider_subscription_name",
        table_name="subscriptions",
        postgresql_where=sa.text("provider_hash IS NOT NULL"),
        sqlite_where=sa.text("provider_hash IS NOT NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_subscription_user_name"),
        "subscriptions",
        ["user_hash", "name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("subscriptions", "provider_hash")
    op.drop_index("ix_provider_authorizations_user_hash", table_name="provider_authorizations")
    op.drop_table("provider_authorizations")
    op.drop_index(op.f("ix_providers_api_token"), table_name="providers")
    op.drop_table("providers")
    # ### end Alembic commands ###
