"""Adjust database column lengths

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-19 19:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, Sequence[str], None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "config_comments",
        "subscription_token",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=43),
        existing_comment="Subscription this comment belongs to",
        existing_nullable=False,
    )
    op.alter_column(
        "config_comments",
        "config_hash",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=32),
        existing_comment="Config this comment applies to",
        existing_nullable=False,
    )
    op.alter_column(
        "external_cache",
        "url_hash",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=32),
        existing_comment="Blake2b hash of canonical URL",
        existing_nullable=False,
    )
    op.alter_column(
        "provider_authorizations",
        "provider_hash",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=36),
        existing_nullable=False,
    )
    op.alter_column(
        "provider_authorizations",
        "user_hash",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=36),
        existing_nullable=False,
    )
    op.alter_column(
        "providers",
        "provider_hash",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=36),
        existing_comment="Unique public identifier of the provider",
        existing_nullable=False,
    )
    op.alter_column(
        "providers",
        "owner_hash",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=36),
        existing_comment="Hash of the user account that owns this provider",
        existing_nullable=False,
    )
    op.alter_column(
        "providers",
        "provider_name",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=16),
        existing_comment="Unique provider name.",
        existing_nullable=False,
    )
    op.alter_column(
        "providers",
        "api_token",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=43),
        existing_comment="Provider API authentication token",
        existing_nullable=False,
    )
    op.alter_column(
        "proxy_configs",
        "config_hash",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=32),
        existing_comment="Blake2b hash of normalized config (without fragment)",
        existing_nullable=False,
    )
    op.alter_column(
        "proxy_configs",
        "protocol",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=16),
        existing_comment="Proxy protocol (vless, vmess, trojan, ss, etc.)",
        existing_nullable=False,
    )
    op.alter_column(
        "sources",
        "subscription_token",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=43),
        existing_nullable=False,
    )
    op.alter_column(
        "sources",
        "id",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=32),
        existing_comment="Unique identifier for this source within subscription",
        existing_nullable=False,
    )
    op.alter_column(
        "sources",
        "source_type",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=15),
        existing_comment="Type: CONFIG, EXTERNAL_URL, or INTERNAL_TOKEN",
        existing_nullable=False,
    )
    op.alter_column(
        "sources",
        "config_hash",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=32),
        existing_comment="Reference to ProxyConfig (for CONFIG type)",
        existing_nullable=True,
    )
    op.alter_column(
        "sources",
        "internal_token",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=43),
        existing_comment="Token for INTERNAL_TOKEN",
        existing_nullable=True,
    )
    op.alter_column(
        "subscriptions",
        "token",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=43),
        existing_comment="Unique public identifier for subscription",
        existing_nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "user_hash",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=36),
        existing_nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "provider_hash",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=36),
        existing_comment="Provider that owns this subscription. NULL for user-owned subscriptions.",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "user_hash",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=36),
        existing_comment="Stable hash derived from external user ID",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "api_token",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=43),
        existing_comment="API authentication token",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "api_token",
        existing_type=sa.String(length=43),
        type_=sa.VARCHAR(length=255),
        existing_comment="API authentication token",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "user_hash",
        existing_type=sa.String(length=36),
        type_=sa.VARCHAR(length=255),
        existing_comment="Stable hash derived from external user ID",
        existing_nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "provider_hash",
        existing_type=sa.String(length=36),
        type_=sa.VARCHAR(length=255),
        existing_comment="Provider that owns this subscription. NULL for user-owned subscriptions.",
        existing_nullable=True,
    )
    op.alter_column(
        "subscriptions",
        "user_hash",
        existing_type=sa.String(length=36),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "token",
        existing_type=sa.String(length=43),
        type_=sa.VARCHAR(length=255),
        existing_comment="Unique public identifier for subscription",
        existing_nullable=False,
    )
    op.alter_column(
        "sources",
        "internal_token",
        existing_type=sa.String(length=43),
        type_=sa.VARCHAR(length=64),
        existing_comment="Token for INTERNAL_TOKEN",
        existing_nullable=True,
    )
    op.alter_column(
        "sources",
        "config_hash",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=64),
        existing_comment="Reference to ProxyConfig (for CONFIG type)",
        existing_nullable=True,
    )
    op.alter_column(
        "sources",
        "source_type",
        existing_type=sa.String(length=15),
        type_=sa.VARCHAR(length=50),
        existing_comment="Type: CONFIG, EXTERNAL_URL, or INTERNAL_TOKEN",
        existing_nullable=False,
    )
    op.alter_column(
        "sources",
        "id",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=64),
        existing_comment="Unique identifier for this source within subscription",
        existing_nullable=False,
    )
    op.alter_column(
        "sources",
        "subscription_token",
        existing_type=sa.String(length=43),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "proxy_configs",
        "protocol",
        existing_type=sa.String(length=16),
        type_=sa.VARCHAR(length=50),
        existing_comment="Proxy protocol (vless, vmess, trojan, ss, etc.)",
        existing_nullable=False,
    )
    op.alter_column(
        "proxy_configs",
        "config_hash",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=64),
        existing_comment="Blake2b hash of normalized config (without fragment)",
        existing_nullable=False,
    )
    op.alter_column(
        "providers",
        "api_token",
        existing_type=sa.String(length=43),
        type_=sa.VARCHAR(length=255),
        existing_comment="Provider API authentication token",
        existing_nullable=False,
    )
    op.alter_column(
        "providers",
        "provider_name",
        existing_type=sa.String(length=16),
        type_=sa.VARCHAR(length=64),
        existing_comment="Unique provider name.",
        existing_nullable=False,
    )
    op.alter_column(
        "providers",
        "owner_hash",
        existing_type=sa.String(length=36),
        type_=sa.VARCHAR(length=255),
        existing_comment="Hash of the user account that owns this provider",
        existing_nullable=False,
    )
    op.alter_column(
        "providers",
        "provider_hash",
        existing_type=sa.String(length=36),
        type_=sa.VARCHAR(length=255),
        existing_comment="Unique public identifier of the provider",
        existing_nullable=False,
    )
    op.alter_column(
        "provider_authorizations",
        "user_hash",
        existing_type=sa.String(length=36),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "provider_authorizations",
        "provider_hash",
        existing_type=sa.String(length=36),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "external_cache",
        "url_hash",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=64),
        existing_comment="Blake2b hash of canonical URL",
        existing_nullable=False,
    )
    op.alter_column(
        "config_comments",
        "config_hash",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=64),
        existing_comment="Config this comment applies to",
        existing_nullable=False,
    )
    op.alter_column(
        "config_comments",
        "subscription_token",
        existing_type=sa.String(length=43),
        type_=sa.VARCHAR(length=255),
        existing_comment="Subscription this comment belongs to",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
